// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: business/business.proto

package businesspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalBusinessStatus int32

const (
	InternalBusinessStatus_INTERNAL_ENGINE__SUCCESS InternalBusinessStatus = 0 //服务正常
	InternalBusinessStatus_INTERNAL_ENGINE__ERROR   InternalBusinessStatus = 1 //服务异常
)

// Enum value maps for InternalBusinessStatus.
var (
	InternalBusinessStatus_name = map[int32]string{
		0: "INTERNAL_ENGINE__SUCCESS",
		1: "INTERNAL_ENGINE__ERROR",
	}
	InternalBusinessStatus_value = map[string]int32{
		"INTERNAL_ENGINE__SUCCESS": 0,
		"INTERNAL_ENGINE__ERROR":   1,
	}
)

func (x InternalBusinessStatus) Enum() *InternalBusinessStatus {
	p := new(InternalBusinessStatus)
	*p = x
	return p
}

func (x InternalBusinessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalBusinessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_business_business_proto_enumTypes[0].Descriptor()
}

func (InternalBusinessStatus) Type() protoreflect.EnumType {
	return &file_business_business_proto_enumTypes[0]
}

func (x InternalBusinessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalBusinessStatus.Descriptor instead.
func (InternalBusinessStatus) EnumDescriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{0}
}

type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl    string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Banner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Banner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BannerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Banner `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *BannerList) Reset() {
	*x = BannerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerList) ProtoMessage() {}

func (x *BannerList) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerList.ProtoReflect.Descriptor instead.
func (*BannerList) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1}
}

func (x *BannerList) GetResults() []*Banner {
	if x != nil {
		return x.Results
	}
	return nil
}

//获取Banner
type GetBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetBannerRequest) Reset() {
	*x = GetBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannerRequest) ProtoMessage() {}

func (x *GetBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannerRequest.ProtoReflect.Descriptor instead.
func (*GetBannerRequest) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{2}
}

func (x *GetBannerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  InternalBusinessStatus `protobuf:"varint,1,opt,name=status,proto3,enum=business.api.InternalBusinessStatus" json:"status,omitempty"`
	Banners *BannerList            `protobuf:"bytes,2,opt,name=banners,proto3" json:"banners,omitempty"`
}

func (x *GetBannerResponse) Reset() {
	*x = GetBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannerResponse) ProtoMessage() {}

func (x *GetBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannerResponse.ProtoReflect.Descriptor instead.
func (*GetBannerResponse) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{3}
}

func (x *GetBannerResponse) GetStatus() InternalBusinessStatus {
	if x != nil {
		return x.Status
	}
	return InternalBusinessStatus_INTERNAL_ENGINE__SUCCESS
}

func (x *GetBannerResponse) GetBanners() *BannerList {
	if x != nil {
		return x.Banners
	}
	return nil
}

type TokenIcon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress   string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	SmallImageUrl  string `protobuf:"bytes,2,opt,name=small_image_url,json=smallImageUrl,proto3" json:"small_image_url,omitempty"`
	MiddleImageUrl string `protobuf:"bytes,3,opt,name=middle_image_url,json=middleImageUrl,proto3" json:"middle_image_url,omitempty"`
	LargeImageUrl  string `protobuf:"bytes,4,opt,name=large_image_url,json=largeImageUrl,proto3" json:"large_image_url,omitempty"`
}

func (x *TokenIcon) Reset() {
	*x = TokenIcon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIcon) ProtoMessage() {}

func (x *TokenIcon) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIcon.ProtoReflect.Descriptor instead.
func (*TokenIcon) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{4}
}

func (x *TokenIcon) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenIcon) GetSmallImageUrl() string {
	if x != nil {
		return x.SmallImageUrl
	}
	return ""
}

func (x *TokenIcon) GetMiddleImageUrl() string {
	if x != nil {
		return x.MiddleImageUrl
	}
	return ""
}

func (x *TokenIcon) GetLargeImageUrl() string {
	if x != nil {
		return x.LargeImageUrl
	}
	return ""
}

type DexIcon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain          string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Dex            string `protobuf:"bytes,2,opt,name=dex,proto3" json:"dex,omitempty"`
	Version        string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	SmallImageUrl  string `protobuf:"bytes,4,opt,name=small_image_url,json=smallImageUrl,proto3" json:"small_image_url,omitempty"`
	MiddleImageUrl string `protobuf:"bytes,5,opt,name=middle_image_url,json=middleImageUrl,proto3" json:"middle_image_url,omitempty"`
	LargeImageUrl  string `protobuf:"bytes,6,opt,name=large_image_url,json=largeImageUrl,proto3" json:"large_image_url,omitempty"`
}

func (x *DexIcon) Reset() {
	*x = DexIcon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DexIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DexIcon) ProtoMessage() {}

func (x *DexIcon) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DexIcon.ProtoReflect.Descriptor instead.
func (*DexIcon) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{5}
}

func (x *DexIcon) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *DexIcon) GetDex() string {
	if x != nil {
		return x.Dex
	}
	return ""
}

func (x *DexIcon) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DexIcon) GetSmallImageUrl() string {
	if x != nil {
		return x.SmallImageUrl
	}
	return ""
}

func (x *DexIcon) GetMiddleImageUrl() string {
	if x != nil {
		return x.MiddleImageUrl
	}
	return ""
}

func (x *DexIcon) GetLargeImageUrl() string {
	if x != nil {
		return x.LargeImageUrl
	}
	return ""
}

type IconList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenIcons []*TokenIcon `protobuf:"bytes,1,rep,name=token_icons,json=tokenIcons,proto3" json:"token_icons,omitempty"`
	DexIcons   []*DexIcon   `protobuf:"bytes,2,rep,name=dex_icons,json=dexIcons,proto3" json:"dex_icons,omitempty"`
}

func (x *IconList) Reset() {
	*x = IconList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IconList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IconList) ProtoMessage() {}

func (x *IconList) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IconList.ProtoReflect.Descriptor instead.
func (*IconList) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{6}
}

func (x *IconList) GetTokenIcons() []*TokenIcon {
	if x != nil {
		return x.TokenIcons
	}
	return nil
}

func (x *IconList) GetDexIcons() []*DexIcon {
	if x != nil {
		return x.DexIcons
	}
	return nil
}

type TokenIconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
}

func (x *TokenIconRequest) Reset() {
	*x = TokenIconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIconRequest) ProtoMessage() {}

func (x *TokenIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIconRequest.ProtoReflect.Descriptor instead.
func (*TokenIconRequest) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{7}
}

func (x *TokenIconRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type DexIconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain   string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Dex     string `protobuf:"bytes,2,opt,name=dex,proto3" json:"dex,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DexIconRequest) Reset() {
	*x = DexIconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DexIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DexIconRequest) ProtoMessage() {}

func (x *DexIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DexIconRequest.ProtoReflect.Descriptor instead.
func (*DexIconRequest) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{8}
}

func (x *DexIconRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *DexIconRequest) GetDex() string {
	if x != nil {
		return x.Dex
	}
	return ""
}

func (x *DexIconRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

//获取Icon
type GetIconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenIcon []*TokenIconRequest `protobuf:"bytes,1,rep,name=token_icon,json=tokenIcon,proto3" json:"token_icon,omitempty"`
	DexIcon   []*DexIconRequest   `protobuf:"bytes,2,rep,name=dex_icon,json=dexIcon,proto3" json:"dex_icon,omitempty"`
}

func (x *GetIconRequest) Reset() {
	*x = GetIconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIconRequest) ProtoMessage() {}

func (x *GetIconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIconRequest.ProtoReflect.Descriptor instead.
func (*GetIconRequest) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{9}
}

func (x *GetIconRequest) GetTokenIcon() []*TokenIconRequest {
	if x != nil {
		return x.TokenIcon
	}
	return nil
}

func (x *GetIconRequest) GetDexIcon() []*DexIconRequest {
	if x != nil {
		return x.DexIcon
	}
	return nil
}

type GetIconResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status InternalBusinessStatus `protobuf:"varint,1,opt,name=status,proto3,enum=business.api.InternalBusinessStatus" json:"status,omitempty"`
	Icons  *IconList              `protobuf:"bytes,2,opt,name=icons,proto3" json:"icons,omitempty"`
}

func (x *GetIconResponse) Reset() {
	*x = GetIconResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIconResponse) ProtoMessage() {}

func (x *GetIconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIconResponse.ProtoReflect.Descriptor instead.
func (*GetIconResponse) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{10}
}

func (x *GetIconResponse) GetStatus() InternalBusinessStatus {
	if x != nil {
		return x.Status
	}
	return InternalBusinessStatus_INTERNAL_ENGINE__SUCCESS
}

func (x *GetIconResponse) GetIcons() *IconList {
	if x != nil {
		return x.Icons
	}
	return nil
}

var File_business_business_proto protoreflect.FileDescriptor

var file_business_business_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2f, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x5d, 0x0a, 0x06, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3c, 0x0a, 0x0a, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x22, 0x2c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x85, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22, 0xaa, 0x01, 0x0a, 0x09, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a,
	0x0f, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x5f,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0xc5, 0x01, 0x0a, 0x07, 0x44, 0x65, 0x78, 0x49,
	0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x28, 0x0a,
	0x10, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x72, 0x67, 0x65,
	0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22,
	0x78, 0x0a, 0x08, 0x49, 0x63, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0b, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x49, 0x63, 0x6f, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x09, 0x64, 0x65, 0x78, 0x5f, 0x69, 0x63, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x78, 0x49, 0x63, 0x6f, 0x6e, 0x52,
	0x08, 0x64, 0x65, 0x78, 0x49, 0x63, 0x6f, 0x6e, 0x73, 0x22, 0x37, 0x0a, 0x10, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x52, 0x0a, 0x0e, 0x44, 0x65, 0x78, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x63,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x09, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x08, 0x64, 0x65, 0x78, 0x5f,
	0x69, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x78, 0x49, 0x63, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x64, 0x65, 0x78, 0x49, 0x63, 0x6f,
	0x6e, 0x22, 0x7d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x49, 0x63, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x73,
	0x2a, 0x52, 0x0a, 0x16, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x49, 0x4e,
	0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45, 0x5f, 0x5f, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x49, 0x4e, 0x54, 0x45,
	0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45, 0x5f, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x01, 0x32, 0xa4, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x12, 0x4e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1e,
	0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x48, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x49,
	0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x63, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x3b, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_business_business_proto_rawDescOnce sync.Once
	file_business_business_proto_rawDescData = file_business_business_proto_rawDesc
)

func file_business_business_proto_rawDescGZIP() []byte {
	file_business_business_proto_rawDescOnce.Do(func() {
		file_business_business_proto_rawDescData = protoimpl.X.CompressGZIP(file_business_business_proto_rawDescData)
	})
	return file_business_business_proto_rawDescData
}

var file_business_business_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_business_business_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_business_business_proto_goTypes = []interface{}{
	(InternalBusinessStatus)(0), // 0: business.api.InternalBusinessStatus
	(*Banner)(nil),              // 1: business.api.Banner
	(*BannerList)(nil),          // 2: business.api.BannerList
	(*GetBannerRequest)(nil),    // 3: business.api.GetBannerRequest
	(*GetBannerResponse)(nil),   // 4: business.api.GetBannerResponse
	(*TokenIcon)(nil),           // 5: business.api.TokenIcon
	(*DexIcon)(nil),             // 6: business.api.DexIcon
	(*IconList)(nil),            // 7: business.api.IconList
	(*TokenIconRequest)(nil),    // 8: business.api.TokenIconRequest
	(*DexIconRequest)(nil),      // 9: business.api.DexIconRequest
	(*GetIconRequest)(nil),      // 10: business.api.GetIconRequest
	(*GetIconResponse)(nil),     // 11: business.api.GetIconResponse
}
var file_business_business_proto_depIdxs = []int32{
	1,  // 0: business.api.BannerList.results:type_name -> business.api.Banner
	0,  // 1: business.api.GetBannerResponse.status:type_name -> business.api.InternalBusinessStatus
	2,  // 2: business.api.GetBannerResponse.banners:type_name -> business.api.BannerList
	5,  // 3: business.api.IconList.token_icons:type_name -> business.api.TokenIcon
	6,  // 4: business.api.IconList.dex_icons:type_name -> business.api.DexIcon
	8,  // 5: business.api.GetIconRequest.token_icon:type_name -> business.api.TokenIconRequest
	9,  // 6: business.api.GetIconRequest.dex_icon:type_name -> business.api.DexIconRequest
	0,  // 7: business.api.GetIconResponse.status:type_name -> business.api.InternalBusinessStatus
	7,  // 8: business.api.GetIconResponse.icons:type_name -> business.api.IconList
	3,  // 9: business.api.Business.GetBanner:input_type -> business.api.GetBannerRequest
	10, // 10: business.api.Business.GetIcon:input_type -> business.api.GetIconRequest
	4,  // 11: business.api.Business.GetBanner:output_type -> business.api.GetBannerResponse
	11, // 12: business.api.Business.GetIcon:output_type -> business.api.GetIconResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_business_business_proto_init() }
func file_business_business_proto_init() {
	if File_business_business_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_business_business_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenIcon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DexIcon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IconList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenIconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DexIconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIconResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_business_business_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_business_proto_goTypes,
		DependencyIndexes: file_business_business_proto_depIdxs,
		EnumInfos:         file_business_business_proto_enumTypes,
		MessageInfos:      file_business_business_proto_msgTypes,
	}.Build()
	File_business_business_proto = out.File
	file_business_business_proto_rawDesc = nil
	file_business_business_proto_goTypes = nil
	file_business_business_proto_depIdxs = nil
}
