// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: business/business.proto

package businesspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalBusinessStatus int32

const (
	InternalBusinessStatus_INTERNAL_ENGINE__SUCCESS InternalBusinessStatus = 0 //服务正常
	InternalBusinessStatus_INTERNAL_ENGINE__ERROR   InternalBusinessStatus = 1 //服务异常
)

// Enum value maps for InternalBusinessStatus.
var (
	InternalBusinessStatus_name = map[int32]string{
		0: "INTERNAL_ENGINE__SUCCESS",
		1: "INTERNAL_ENGINE__ERROR",
	}
	InternalBusinessStatus_value = map[string]int32{
		"INTERNAL_ENGINE__SUCCESS": 0,
		"INTERNAL_ENGINE__ERROR":   1,
	}
)

func (x InternalBusinessStatus) Enum() *InternalBusinessStatus {
	p := new(InternalBusinessStatus)
	*p = x
	return p
}

func (x InternalBusinessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalBusinessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_business_business_proto_enumTypes[0].Descriptor()
}

func (InternalBusinessStatus) Type() protoreflect.EnumType {
	return &file_business_business_proto_enumTypes[0]
}

func (x InternalBusinessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalBusinessStatus.Descriptor instead.
func (InternalBusinessStatus) EnumDescriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{0}
}

type Banner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerId    int64  `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	ImageUrl    string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	OnLine      bool   `protobuf:"varint,5,opt,name=on_line,json=onLine,proto3" json:"on_line,omitempty"`
}

func (x *Banner) Reset() {
	*x = Banner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *Banner) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Banner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Banner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Banner) GetOnLine() bool {
	if x != nil {
		return x.OnLine
	}
	return false
}

type BannerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Banner `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *BannerList) Reset() {
	*x = BannerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerList) ProtoMessage() {}

func (x *BannerList) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerList.ProtoReflect.Descriptor instead.
func (*BannerList) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1}
}

func (x *BannerList) GetResults() []*Banner {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetBannersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBannersRequest) Reset() {
	*x = GetBannersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBannersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannersRequest) ProtoMessage() {}

func (x *GetBannersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannersRequest.ProtoReflect.Descriptor instead.
func (*GetBannersRequest) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{2}
}

type GetBannersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  InternalBusinessStatus `protobuf:"varint,1,opt,name=status,proto3,enum=business.api.InternalBusinessStatus" json:"status,omitempty"`
	Banners *BannerList            `protobuf:"bytes,2,opt,name=banners,proto3" json:"banners,omitempty"`
}

func (x *GetBannersResponse) Reset() {
	*x = GetBannersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBannersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBannersResponse) ProtoMessage() {}

func (x *GetBannersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBannersResponse.ProtoReflect.Descriptor instead.
func (*GetBannersResponse) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{3}
}

func (x *GetBannersResponse) GetStatus() InternalBusinessStatus {
	if x != nil {
		return x.Status
	}
	return InternalBusinessStatus_INTERNAL_ENGINE__SUCCESS
}

func (x *GetBannersResponse) GetBanners() *BannerList {
	if x != nil {
		return x.Banners
	}
	return nil
}

type TokenIcon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenIconId      int64  `protobuf:"varint,1,opt,name=token_icon_id,json=tokenIconId,proto3" json:"token_icon_id,omitempty"`
	TokenName        string `protobuf:"bytes,2,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	Chain            string `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	TokenAddress     string `protobuf:"bytes,4,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	SmallIconBase64  string `protobuf:"bytes,5,opt,name=small_icon_base64,json=smallIconBase64,proto3" json:"small_icon_base64,omitempty"`
	MiddleIconBase64 string `protobuf:"bytes,6,opt,name=middle_icon_base64,json=middleIconBase64,proto3" json:"middle_icon_base64,omitempty"`
	LargeIconBase64  string `protobuf:"bytes,7,opt,name=large_icon_base64,json=largeIconBase64,proto3" json:"large_icon_base64,omitempty"`
}

func (x *TokenIcon) Reset() {
	*x = TokenIcon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIcon) ProtoMessage() {}

func (x *TokenIcon) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIcon.ProtoReflect.Descriptor instead.
func (*TokenIcon) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{4}
}

func (x *TokenIcon) GetTokenIconId() int64 {
	if x != nil {
		return x.TokenIconId
	}
	return 0
}

func (x *TokenIcon) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *TokenIcon) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *TokenIcon) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenIcon) GetSmallIconBase64() string {
	if x != nil {
		return x.SmallIconBase64
	}
	return ""
}

func (x *TokenIcon) GetMiddleIconBase64() string {
	if x != nil {
		return x.MiddleIconBase64
	}
	return ""
}

func (x *TokenIcon) GetLargeIconBase64() string {
	if x != nil {
		return x.LargeIconBase64
	}
	return ""
}

type IconList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenIcons []*TokenIcon `protobuf:"bytes,1,rep,name=token_icons,json=tokenIcons,proto3" json:"token_icons,omitempty"`
}

func (x *IconList) Reset() {
	*x = IconList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IconList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IconList) ProtoMessage() {}

func (x *IconList) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IconList.ProtoReflect.Descriptor instead.
func (*IconList) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{5}
}

func (x *IconList) GetTokenIcons() []*TokenIcon {
	if x != nil {
		return x.TokenIcons
	}
	return nil
}

type GetTokenIconsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
}

func (x *GetTokenIconsRequest) Reset() {
	*x = GetTokenIconsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenIconsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenIconsRequest) ProtoMessage() {}

func (x *GetTokenIconsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenIconsRequest.ProtoReflect.Descriptor instead.
func (*GetTokenIconsRequest) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{6}
}

func (x *GetTokenIconsRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type GetTokenIconsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status InternalBusinessStatus `protobuf:"varint,1,opt,name=status,proto3,enum=business.api.InternalBusinessStatus" json:"status,omitempty"`
	Icons  *IconList              `protobuf:"bytes,2,opt,name=icons,proto3" json:"icons,omitempty"`
}

func (x *GetTokenIconsResponse) Reset() {
	*x = GetTokenIconsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenIconsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenIconsResponse) ProtoMessage() {}

func (x *GetTokenIconsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenIconsResponse.ProtoReflect.Descriptor instead.
func (*GetTokenIconsResponse) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{7}
}

func (x *GetTokenIconsResponse) GetStatus() InternalBusinessStatus {
	if x != nil {
		return x.Status
	}
	return InternalBusinessStatus_INTERNAL_ENGINE__SUCCESS
}

func (x *GetTokenIconsResponse) GetIcons() *IconList {
	if x != nil {
		return x.Icons
	}
	return nil
}

type AddTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenName    string `protobuf:"bytes,1,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	Chain        string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	TokenAddress string `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
}

func (x *AddTokenRequest) Reset() {
	*x = AddTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTokenRequest) ProtoMessage() {}

func (x *AddTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTokenRequest.ProtoReflect.Descriptor instead.
func (*AddTokenRequest) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{8}
}

func (x *AddTokenRequest) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *AddTokenRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *AddTokenRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type AddTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status InternalBusinessStatus `protobuf:"varint,1,opt,name=status,proto3,enum=business.api.InternalBusinessStatus" json:"status,omitempty"`
}

func (x *AddTokenResponse) Reset() {
	*x = AddTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_business_business_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTokenResponse) ProtoMessage() {}

func (x *AddTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTokenResponse.ProtoReflect.Descriptor instead.
func (*AddTokenResponse) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{9}
}

func (x *AddTokenResponse) GetStatus() InternalBusinessStatus {
	if x != nil {
		return x.Status
	}
	return InternalBusinessStatus_INTERNAL_ENGINE__SUCCESS
}

var File_business_business_proto protoreflect.FileDescriptor

var file_business_business_proto_rawDesc = []byte{
	0x0a, 0x17, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2f, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x93, 0x01, 0x0a, 0x06, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x3c, 0x0a,
	0x0a, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x86, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x07, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x8f, 0x02, 0x0a, 0x09, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x69,
	0x63, 0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x63, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x36,
	0x34, 0x12, 0x2c, 0x0a, 0x12, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x5f, 0x69, 0x63, 0x6f, 0x6e,
	0x5f, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d,
	0x69, 0x64, 0x64, 0x6c, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x12,
	0x2a, 0x0a, 0x11, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x62, 0x61,
	0x73, 0x65, 0x36, 0x34, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x61, 0x72, 0x67,
	0x65, 0x49, 0x63, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x36, 0x34, 0x22, 0x44, 0x0a, 0x08, 0x49,
	0x63, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x52, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e,
	0x73, 0x22, 0x3b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x83,
	0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x63, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x69,
	0x63, 0x6f, 0x6e, 0x73, 0x22, 0x6b, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x0d,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0x50, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2a, 0x52, 0x0a, 0x16, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x42,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a,
	0x18, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45,
	0x5f, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x49,
	0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45, 0x5f, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0x86, 0x02, 0x0a, 0x08, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x12, 0x51, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x73, 0x12, 0x1f, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x49, 0x63, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x63, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1d, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_business_business_proto_rawDescOnce sync.Once
	file_business_business_proto_rawDescData = file_business_business_proto_rawDesc
)

func file_business_business_proto_rawDescGZIP() []byte {
	file_business_business_proto_rawDescOnce.Do(func() {
		file_business_business_proto_rawDescData = protoimpl.X.CompressGZIP(file_business_business_proto_rawDescData)
	})
	return file_business_business_proto_rawDescData
}

var file_business_business_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_business_business_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_business_business_proto_goTypes = []interface{}{
	(InternalBusinessStatus)(0),   // 0: business.api.InternalBusinessStatus
	(*Banner)(nil),                // 1: business.api.Banner
	(*BannerList)(nil),            // 2: business.api.BannerList
	(*GetBannersRequest)(nil),     // 3: business.api.GetBannersRequest
	(*GetBannersResponse)(nil),    // 4: business.api.GetBannersResponse
	(*TokenIcon)(nil),             // 5: business.api.TokenIcon
	(*IconList)(nil),              // 6: business.api.IconList
	(*GetTokenIconsRequest)(nil),  // 7: business.api.GetTokenIconsRequest
	(*GetTokenIconsResponse)(nil), // 8: business.api.GetTokenIconsResponse
	(*AddTokenRequest)(nil),       // 9: business.api.AddTokenRequest
	(*AddTokenResponse)(nil),      // 10: business.api.AddTokenResponse
}
var file_business_business_proto_depIdxs = []int32{
	1,  // 0: business.api.BannerList.results:type_name -> business.api.Banner
	0,  // 1: business.api.GetBannersResponse.status:type_name -> business.api.InternalBusinessStatus
	2,  // 2: business.api.GetBannersResponse.banners:type_name -> business.api.BannerList
	5,  // 3: business.api.IconList.token_icons:type_name -> business.api.TokenIcon
	0,  // 4: business.api.GetTokenIconsResponse.status:type_name -> business.api.InternalBusinessStatus
	6,  // 5: business.api.GetTokenIconsResponse.icons:type_name -> business.api.IconList
	0,  // 6: business.api.AddTokenResponse.status:type_name -> business.api.InternalBusinessStatus
	3,  // 7: business.api.Business.GetBanners:input_type -> business.api.GetBannersRequest
	7,  // 8: business.api.Business.GetTokenIcons:input_type -> business.api.GetTokenIconsRequest
	9,  // 9: business.api.Business.AddToken:input_type -> business.api.AddTokenRequest
	4,  // 10: business.api.Business.GetBanners:output_type -> business.api.GetBannersResponse
	8,  // 11: business.api.Business.GetTokenIcons:output_type -> business.api.GetTokenIconsResponse
	10, // 12: business.api.Business.AddToken:output_type -> business.api.AddTokenResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_business_business_proto_init() }
func file_business_business_proto_init() {
	if File_business_business_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_business_business_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBannersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBannersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenIcon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IconList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenIconsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenIconsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_business_business_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_business_business_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_business_proto_goTypes,
		DependencyIndexes: file_business_business_proto_depIdxs,
		EnumInfos:         file_business_business_proto_enumTypes,
		MessageInfos:      file_business_business_proto_msgTypes,
	}.Build()
	File_business_business_proto = out.File
	file_business_business_proto_rawDesc = nil
	file_business_business_proto_goTypes = nil
	file_business_business_proto_depIdxs = nil
}
