// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: token/token.proto

package tokenpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InternalEngineStatus int32

const (
	InternalEngineStatus_INTERNAL_ENGINE__SUCCESS InternalEngineStatus = 0 //服务正常
	InternalEngineStatus_INTERNAL_ENGINE__ERROR   InternalEngineStatus = 1 //服务异常
)

// Enum value maps for InternalEngineStatus.
var (
	InternalEngineStatus_name = map[int32]string{
		0: "INTERNAL_ENGINE__SUCCESS",
		1: "INTERNAL_ENGINE__ERROR",
	}
	InternalEngineStatus_value = map[string]int32{
		"INTERNAL_ENGINE__SUCCESS": 0,
		"INTERNAL_ENGINE__ERROR":   1,
	}
)

func (x InternalEngineStatus) Enum() *InternalEngineStatus {
	p := new(InternalEngineStatus)
	*p = x
	return p
}

func (x InternalEngineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InternalEngineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_token_token_proto_enumTypes[0].Descriptor()
}

func (InternalEngineStatus) Type() protoreflect.EnumType {
	return &file_token_token_proto_enumTypes[0]
}

func (x InternalEngineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InternalEngineStatus.Descriptor instead.
func (InternalEngineStatus) EnumDescriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{0}
}

type Dex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain   string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`     //链eth, bsc,
	Dex     string `protobuf:"bytes,2,opt,name=dex,proto3" json:"dex,omitempty"`         //交易所 sushi, uniswap, pancake
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // 版本号 uniswap 分为v2，v3
}

func (x *Dex) Reset() {
	*x = Dex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dex) ProtoMessage() {}

func (x *Dex) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dex.ProtoReflect.Descriptor instead.
func (*Dex) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{0}
}

func (x *Dex) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Dex) GetDex() string {
	if x != nil {
		return x.Dex
	}
	return ""
}

func (x *Dex) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeStamp   int64  `protobuf:"varint,1,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	PingMessage string `protobuf:"bytes,2,opt,name=ping_message,json=pingMessage,proto3" json:"ping_message,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{1}
}

func (x *Ping) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *Ping) GetPingMessage() string {
	if x != nil {
		return x.PingMessage
	}
	return ""
}

type Hot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TokenName    string  `protobuf:"bytes,2,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`          // 币种
	TokenAddress string  `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"` // 币的地址，通常是0x开头
	Price        float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`                                 //价格，美元为单位
	Increase_24H float64 `protobuf:"fixed64,5,opt,name=increase_24h,json=increase24h,proto3" json:"increase_24h,omitempty"`  //24h增幅
	Increase_7D  float64 `protobuf:"fixed64,6,opt,name=increase_7d,json=increase7d,proto3" json:"increase_7d,omitempty"`     //7天增幅
	Increase_30D float64 `protobuf:"fixed64,7,opt,name=increase_30d,json=increase30d,proto3" json:"increase_30d,omitempty"`  //30天增幅
	Volume       float64 `protobuf:"fixed64,8,opt,name=volume,proto3" json:"volume,omitempty"`                               //成交量 sum(数量*价格)
	Dex          *Dex    `protobuf:"bytes,9,opt,name=dex,proto3" json:"dex,omitempty"`
}

func (x *Hot) Reset() {
	*x = Hot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hot) ProtoMessage() {}

func (x *Hot) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hot.ProtoReflect.Descriptor instead.
func (*Hot) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{2}
}

func (x *Hot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hot) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *Hot) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *Hot) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Hot) GetIncrease_24H() float64 {
	if x != nil {
		return x.Increase_24H
	}
	return 0
}

func (x *Hot) GetIncrease_7D() float64 {
	if x != nil {
		return x.Increase_7D
	}
	return 0
}

func (x *Hot) GetIncrease_30D() float64 {
	if x != nil {
		return x.Increase_30D
	}
	return 0
}

func (x *Hot) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Hot) GetDex() *Dex {
	if x != nil {
		return x.Dex
	}
	return nil
}

type HotList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hot []*Hot `protobuf:"bytes,1,rep,name=hot,proto3" json:"hot,omitempty"`
}

func (x *HotList) Reset() {
	*x = HotList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotList) ProtoMessage() {}

func (x *HotList) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotList.ProtoReflect.Descriptor instead.
func (*HotList) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{3}
}

func (x *HotList) GetHot() []*Hot {
	if x != nil {
		return x.Hot
	}
	return nil
}

type SubscribeHotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeHotRequest) Reset() {
	*x = SubscribeHotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeHotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeHotRequest) ProtoMessage() {}

func (x *SubscribeHotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeHotRequest.ProtoReflect.Descriptor instead.
func (*SubscribeHotRequest) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{4}
}

type SubscribeHotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status InternalEngineStatus `protobuf:"varint,1,opt,name=status,proto3,enum=token.api.InternalEngineStatus" json:"status,omitempty"`
	// Types that are assignable to Msg:
	//	*SubscribeHotResponse_HotList
	//	*SubscribeHotResponse_Ping
	Msg isSubscribeHotResponse_Msg `protobuf_oneof:"msg"`
}

func (x *SubscribeHotResponse) Reset() {
	*x = SubscribeHotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeHotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeHotResponse) ProtoMessage() {}

func (x *SubscribeHotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeHotResponse.ProtoReflect.Descriptor instead.
func (*SubscribeHotResponse) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeHotResponse) GetStatus() InternalEngineStatus {
	if x != nil {
		return x.Status
	}
	return InternalEngineStatus_INTERNAL_ENGINE__SUCCESS
}

func (m *SubscribeHotResponse) GetMsg() isSubscribeHotResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *SubscribeHotResponse) GetHotList() *HotList {
	if x, ok := x.GetMsg().(*SubscribeHotResponse_HotList); ok {
		return x.HotList
	}
	return nil
}

func (x *SubscribeHotResponse) GetPing() *Ping {
	if x, ok := x.GetMsg().(*SubscribeHotResponse_Ping); ok {
		return x.Ping
	}
	return nil
}

type isSubscribeHotResponse_Msg interface {
	isSubscribeHotResponse_Msg()
}

type SubscribeHotResponse_HotList struct {
	HotList *HotList `protobuf:"bytes,2,opt,name=hot_list,json=hotList,proto3,oneof"`
}

type SubscribeHotResponse_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*SubscribeHotResponse_HotList) isSubscribeHotResponse_Msg() {}

func (*SubscribeHotResponse_Ping) isSubscribeHotResponse_Msg() {}

type NewToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price               float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	TokenName           string  `protobuf:"bytes,3,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	CreateTime          int64   `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Liquidity           float64 `protobuf:"fixed64,5,opt,name=liquidity,proto3" json:"liquidity,omitempty"`
	Volume_24H          float64 `protobuf:"fixed64,6,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	Increase_1H         float64 `protobuf:"fixed64,7,opt,name=increase_1h,json=increase1h,proto3" json:"increase_1h,omitempty"`
	TokenAddress        string  `protobuf:"bytes,8,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	PairContractAddress string  `protobuf:"bytes,9,opt,name=pair_contract_address,json=pairContractAddress,proto3" json:"pair_contract_address,omitempty"`
	Dex                 *Dex    `protobuf:"bytes,10,opt,name=dex,proto3" json:"dex,omitempty"`
}

func (x *NewToken) Reset() {
	*x = NewToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewToken) ProtoMessage() {}

func (x *NewToken) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewToken.ProtoReflect.Descriptor instead.
func (*NewToken) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{6}
}

func (x *NewToken) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewToken) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *NewToken) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *NewToken) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *NewToken) GetLiquidity() float64 {
	if x != nil {
		return x.Liquidity
	}
	return 0
}

func (x *NewToken) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *NewToken) GetIncrease_1H() float64 {
	if x != nil {
		return x.Increase_1H
	}
	return 0
}

func (x *NewToken) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *NewToken) GetPairContractAddress() string {
	if x != nil {
		return x.PairContractAddress
	}
	return ""
}

func (x *NewToken) GetDex() *Dex {
	if x != nil {
		return x.Dex
	}
	return nil
}

type NewTokenList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewToken []*NewToken `protobuf:"bytes,1,rep,name=new_token,json=newToken,proto3" json:"new_token,omitempty"`
}

func (x *NewTokenList) Reset() {
	*x = NewTokenList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTokenList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTokenList) ProtoMessage() {}

func (x *NewTokenList) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTokenList.ProtoReflect.Descriptor instead.
func (*NewTokenList) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{7}
}

func (x *NewTokenList) GetNewToken() []*NewToken {
	if x != nil {
		return x.NewToken
	}
	return nil
}

// 订阅NewPair
type SubscribeNewPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeNewPairRequest) Reset() {
	*x = SubscribeNewPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeNewPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeNewPairRequest) ProtoMessage() {}

func (x *SubscribeNewPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeNewPairRequest.ProtoReflect.Descriptor instead.
func (*SubscribeNewPairRequest) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{8}
}

type SubscribeNewPairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status InternalEngineStatus `protobuf:"varint,1,opt,name=status,proto3,enum=token.api.InternalEngineStatus" json:"status,omitempty"`
	// Types that are assignable to Msg:
	//	*SubscribeNewPairResponse_NewTokenList
	//	*SubscribeNewPairResponse_Ping
	Msg          isSubscribeNewPairResponse_Msg `protobuf_oneof:"msg"`
	NewPairCount int64                          `protobuf:"varint,4,opt,name=new_pair_count,json=newPairCount,proto3" json:"new_pair_count,omitempty"`
}

func (x *SubscribeNewPairResponse) Reset() {
	*x = SubscribeNewPairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeNewPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeNewPairResponse) ProtoMessage() {}

func (x *SubscribeNewPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeNewPairResponse.ProtoReflect.Descriptor instead.
func (*SubscribeNewPairResponse) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeNewPairResponse) GetStatus() InternalEngineStatus {
	if x != nil {
		return x.Status
	}
	return InternalEngineStatus_INTERNAL_ENGINE__SUCCESS
}

func (m *SubscribeNewPairResponse) GetMsg() isSubscribeNewPairResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *SubscribeNewPairResponse) GetNewTokenList() *NewTokenList {
	if x, ok := x.GetMsg().(*SubscribeNewPairResponse_NewTokenList); ok {
		return x.NewTokenList
	}
	return nil
}

func (x *SubscribeNewPairResponse) GetPing() *Ping {
	if x, ok := x.GetMsg().(*SubscribeNewPairResponse_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *SubscribeNewPairResponse) GetNewPairCount() int64 {
	if x != nil {
		return x.NewPairCount
	}
	return 0
}

type isSubscribeNewPairResponse_Msg interface {
	isSubscribeNewPairResponse_Msg()
}

type SubscribeNewPairResponse_NewTokenList struct {
	NewTokenList *NewTokenList `protobuf:"bytes,2,opt,name=new_token_list,json=newTokenList,proto3,oneof"`
}

type SubscribeNewPairResponse_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*SubscribeNewPairResponse_NewTokenList) isSubscribeNewPairResponse_Msg() {}

func (*SubscribeNewPairResponse_Ping) isSubscribeNewPairResponse_Msg() {}

type GetNewPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 第几条开始(不是id)
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 不填默认返回300
}

func (x *GetNewPairRequest) Reset() {
	*x = GetNewPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewPairRequest) ProtoMessage() {}

func (x *GetNewPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewPairRequest.ProtoReflect.Descriptor instead.
func (*GetNewPairRequest) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{10}
}

func (x *GetNewPairRequest) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetNewPairRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetNewPairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       InternalEngineStatus `protobuf:"varint,1,opt,name=status,proto3,enum=token.api.InternalEngineStatus" json:"status,omitempty"`
	NewTokenList *NewTokenList        `protobuf:"bytes,2,opt,name=new_token_list,json=newTokenList,proto3" json:"new_token_list,omitempty"`
}

func (x *GetNewPairResponse) Reset() {
	*x = GetNewPairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNewPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewPairResponse) ProtoMessage() {}

func (x *GetNewPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewPairResponse.ProtoReflect.Descriptor instead.
func (*GetNewPairResponse) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{11}
}

func (x *GetNewPairResponse) GetStatus() InternalEngineStatus {
	if x != nil {
		return x.Status
	}
	return InternalEngineStatus_INTERNAL_ENGINE__SUCCESS
}

func (x *GetNewPairResponse) GetNewTokenList() *NewTokenList {
	if x != nil {
		return x.NewTokenList
	}
	return nil
}

type OnNewTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenName    string `protobuf:"bytes,1,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	TokenAddress string `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Ts           int64  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Dex          *Dex   `protobuf:"bytes,4,opt,name=dex,proto3" json:"dex,omitempty"`
}

func (x *OnNewTokenRequest) Reset() {
	*x = OnNewTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnNewTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnNewTokenRequest) ProtoMessage() {}

func (x *OnNewTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnNewTokenRequest.ProtoReflect.Descriptor instead.
func (*OnNewTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{12}
}

func (x *OnNewTokenRequest) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *OnNewTokenRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *OnNewTokenRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *OnNewTokenRequest) GetDex() *Dex {
	if x != nil {
		return x.Dex
	}
	return nil
}

type OnNewTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status InternalEngineStatus `protobuf:"varint,1,opt,name=status,proto3,enum=token.api.InternalEngineStatus" json:"status,omitempty"`
}

func (x *OnNewTokenResponse) Reset() {
	*x = OnNewTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnNewTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnNewTokenResponse) ProtoMessage() {}

func (x *OnNewTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnNewTokenResponse.ProtoReflect.Descriptor instead.
func (*OnNewTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{13}
}

func (x *OnNewTokenResponse) GetStatus() InternalEngineStatus {
	if x != nil {
		return x.Status
	}
	return InternalEngineStatus_INTERNAL_ENGINE__SUCCESS
}

type SearchTokenResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenName    string  `protobuf:"bytes,1,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	TokenAddress string  `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	PriceUsdt    float64 `protobuf:"fixed64,3,opt,name=price_usdt,json=priceUsdt,proto3" json:"price_usdt,omitempty"`
	Increase_1D  float64 `protobuf:"fixed64,4,opt,name=increase_1d,json=increase1d,proto3" json:"increase_1d,omitempty"`
	Dex          *Dex    `protobuf:"bytes,5,opt,name=dex,proto3" json:"dex,omitempty"`
}

func (x *SearchTokenResult) Reset() {
	*x = SearchTokenResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTokenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTokenResult) ProtoMessage() {}

func (x *SearchTokenResult) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTokenResult.ProtoReflect.Descriptor instead.
func (*SearchTokenResult) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{14}
}

func (x *SearchTokenResult) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

func (x *SearchTokenResult) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *SearchTokenResult) GetPriceUsdt() float64 {
	if x != nil {
		return x.PriceUsdt
	}
	return 0
}

func (x *SearchTokenResult) GetIncrease_1D() float64 {
	if x != nil {
		return x.Increase_1D
	}
	return 0
}

func (x *SearchTokenResult) GetDex() *Dex {
	if x != nil {
		return x.Dex
	}
	return nil
}

type SearchTokenResultList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*SearchTokenResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SearchTokenResultList) Reset() {
	*x = SearchTokenResultList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTokenResultList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTokenResultList) ProtoMessage() {}

func (x *SearchTokenResultList) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTokenResultList.ProtoReflect.Descriptor instead.
func (*SearchTokenResultList) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{15}
}

func (x *SearchTokenResultList) GetResults() []*SearchTokenResult {
	if x != nil {
		return x.Results
	}
	return nil
}

//按照关键字查询币，不分交易所
type SearchTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenNameOrAddress string `protobuf:"bytes,1,opt,name=token_name_or_address,json=tokenNameOrAddress,proto3" json:"token_name_or_address,omitempty"`
}

func (x *SearchTokenRequest) Reset() {
	*x = SearchTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTokenRequest) ProtoMessage() {}

func (x *SearchTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTokenRequest.ProtoReflect.Descriptor instead.
func (*SearchTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{16}
}

func (x *SearchTokenRequest) GetTokenNameOrAddress() string {
	if x != nil {
		return x.TokenNameOrAddress
	}
	return ""
}

type SearchTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     InternalEngineStatus   `protobuf:"varint,1,opt,name=status,proto3,enum=token.api.InternalEngineStatus" json:"status,omitempty"`
	ResultList *SearchTokenResultList `protobuf:"bytes,2,opt,name=result_list,json=resultList,proto3" json:"result_list,omitempty"`
}

func (x *SearchTokenResponse) Reset() {
	*x = SearchTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTokenResponse) ProtoMessage() {}

func (x *SearchTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTokenResponse.ProtoReflect.Descriptor instead.
func (*SearchTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{17}
}

func (x *SearchTokenResponse) GetStatus() InternalEngineStatus {
	if x != nil {
		return x.Status
	}
	return InternalEngineStatus_INTERNAL_ENGINE__SUCCESS
}

func (x *SearchTokenResponse) GetResultList() *SearchTokenResultList {
	if x != nil {
		return x.ResultList
	}
	return nil
}

type OnPairSyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token0Name      string  `protobuf:"bytes,1,opt,name=token0_name,json=token0Name,proto3" json:"token0_name,omitempty"`
	Token0Address   string  `protobuf:"bytes,2,opt,name=token0_address,json=token0Address,proto3" json:"token0_address,omitempty"`
	Token1Name      string  `protobuf:"bytes,3,opt,name=token1_name,json=token1Name,proto3" json:"token1_name,omitempty"`
	Token1Address   string  `protobuf:"bytes,4,opt,name=token1_address,json=token1Address,proto3" json:"token1_address,omitempty"`
	Token0Amount    float64 `protobuf:"fixed64,5,opt,name=token0_amount,json=token0Amount,proto3" json:"token0_amount,omitempty"`
	Token1Amount    float64 `protobuf:"fixed64,6,opt,name=token1_amount,json=token1Amount,proto3" json:"token1_amount,omitempty"`
	Ts              int64   `protobuf:"varint,7,opt,name=ts,proto3" json:"ts,omitempty"`
	Value           float64 `protobuf:"fixed64,8,opt,name=value,proto3" json:"value,omitempty"`
	ContractAddress string  `protobuf:"bytes,9,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Dex             *Dex    `protobuf:"bytes,10,opt,name=dex,proto3" json:"dex,omitempty"`
}

func (x *OnPairSyncRequest) Reset() {
	*x = OnPairSyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPairSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPairSyncRequest) ProtoMessage() {}

func (x *OnPairSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPairSyncRequest.ProtoReflect.Descriptor instead.
func (*OnPairSyncRequest) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{18}
}

func (x *OnPairSyncRequest) GetToken0Name() string {
	if x != nil {
		return x.Token0Name
	}
	return ""
}

func (x *OnPairSyncRequest) GetToken0Address() string {
	if x != nil {
		return x.Token0Address
	}
	return ""
}

func (x *OnPairSyncRequest) GetToken1Name() string {
	if x != nil {
		return x.Token1Name
	}
	return ""
}

func (x *OnPairSyncRequest) GetToken1Address() string {
	if x != nil {
		return x.Token1Address
	}
	return ""
}

func (x *OnPairSyncRequest) GetToken0Amount() float64 {
	if x != nil {
		return x.Token0Amount
	}
	return 0
}

func (x *OnPairSyncRequest) GetToken1Amount() float64 {
	if x != nil {
		return x.Token1Amount
	}
	return 0
}

func (x *OnPairSyncRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *OnPairSyncRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *OnPairSyncRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *OnPairSyncRequest) GetDex() *Dex {
	if x != nil {
		return x.Dex
	}
	return nil
}

type OnPairSyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status InternalEngineStatus `protobuf:"varint,1,opt,name=status,proto3,enum=token.api.InternalEngineStatus" json:"status,omitempty"`
}

func (x *OnPairSyncResponse) Reset() {
	*x = OnPairSyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPairSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPairSyncResponse) ProtoMessage() {}

func (x *OnPairSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPairSyncResponse.ProtoReflect.Descriptor instead.
func (*OnPairSyncResponse) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{19}
}

func (x *OnPairSyncResponse) GetStatus() InternalEngineStatus {
	if x != nil {
		return x.Status
	}
	return InternalEngineStatus_INTERNAL_ENGINE__SUCCESS
}

type OnTokenPriceChangedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress string  `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Price        float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Increase_1H  float64 `protobuf:"fixed64,3,opt,name=increase_1h,json=increase1h,proto3" json:"increase_1h,omitempty"`
	Increase_24H float64 `protobuf:"fixed64,4,opt,name=increase_24h,json=increase24h,proto3" json:"increase_24h,omitempty"`
	Increase_7D  float64 `protobuf:"fixed64,5,opt,name=increase_7d,json=increase7d,proto3" json:"increase_7d,omitempty"`
	Increase_30D float64 `protobuf:"fixed64,6,opt,name=increase_30d,json=increase30d,proto3" json:"increase_30d,omitempty"`
	Volume       float64 `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Liquidity    float64 `protobuf:"fixed64,8,opt,name=liquidity,proto3" json:"liquidity,omitempty"`
	Dex          *Dex    `protobuf:"bytes,9,opt,name=dex,proto3" json:"dex,omitempty"`
}

func (x *OnTokenPriceChangedRequest) Reset() {
	*x = OnTokenPriceChangedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTokenPriceChangedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTokenPriceChangedRequest) ProtoMessage() {}

func (x *OnTokenPriceChangedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTokenPriceChangedRequest.ProtoReflect.Descriptor instead.
func (*OnTokenPriceChangedRequest) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{20}
}

func (x *OnTokenPriceChangedRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *OnTokenPriceChangedRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OnTokenPriceChangedRequest) GetIncrease_1H() float64 {
	if x != nil {
		return x.Increase_1H
	}
	return 0
}

func (x *OnTokenPriceChangedRequest) GetIncrease_24H() float64 {
	if x != nil {
		return x.Increase_24H
	}
	return 0
}

func (x *OnTokenPriceChangedRequest) GetIncrease_7D() float64 {
	if x != nil {
		return x.Increase_7D
	}
	return 0
}

func (x *OnTokenPriceChangedRequest) GetIncrease_30D() float64 {
	if x != nil {
		return x.Increase_30D
	}
	return 0
}

func (x *OnTokenPriceChangedRequest) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *OnTokenPriceChangedRequest) GetLiquidity() float64 {
	if x != nil {
		return x.Liquidity
	}
	return 0
}

func (x *OnTokenPriceChangedRequest) GetDex() *Dex {
	if x != nil {
		return x.Dex
	}
	return nil
}

type OnTokenPriceChangedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status InternalEngineStatus `protobuf:"varint,1,opt,name=status,proto3,enum=token.api.InternalEngineStatus" json:"status,omitempty"`
}

func (x *OnTokenPriceChangedResponse) Reset() {
	*x = OnTokenPriceChangedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_token_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTokenPriceChangedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTokenPriceChangedResponse) ProtoMessage() {}

func (x *OnTokenPriceChangedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_token_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTokenPriceChangedResponse.ProtoReflect.Descriptor instead.
func (*OnTokenPriceChangedResponse) Descriptor() ([]byte, []int) {
	return file_token_token_proto_rawDescGZIP(), []int{21}
}

func (x *OnTokenPriceChangedResponse) GetStatus() InternalEngineStatus {
	if x != nil {
		return x.Status
	}
	return InternalEngineStatus_INTERNAL_ENGINE__SUCCESS
}

var File_token_token_proto protoreflect.FileDescriptor

var file_token_token_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x47,
	0x0a, 0x03, 0x44, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x90, 0x02, 0x0a, 0x03, 0x48, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x5f,
	0x32, 0x34, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65,
	0x61, 0x73, 0x65, 0x32, 0x34, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61,
	0x73, 0x65, 0x5f, 0x37, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x69, 0x6e, 0x63,
	0x72, 0x65, 0x61, 0x73, 0x65, 0x37, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x72, 0x65,
	0x61, 0x73, 0x65, 0x5f, 0x33, 0x30, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x69,
	0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x33, 0x30, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x03, 0x64, 0x65, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x78, 0x52,
	0x03, 0x64, 0x65, 0x78, 0x22, 0x2b, 0x0a, 0x07, 0x48, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x03, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x6f, 0x74, 0x52, 0x03, 0x68, 0x6f,
	0x74, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xae, 0x01, 0x0a, 0x14, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x68, 0x6f,
	0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x70,
	0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69,
	0x6e, 0x67, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xc9, 0x02, 0x0a, 0x08, 0x4e, 0x65,
	0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x09, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x32, 0x34, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x32, 0x34, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x63,
	0x72, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x31, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a,
	0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x31, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x32, 0x0a, 0x15, 0x70, 0x61, 0x69, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13,
	0x70, 0x61, 0x69, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x03, 0x64, 0x65, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x78,
	0x52, 0x03, 0x64, 0x65, 0x78, 0x22, 0x40, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x08, 0x6e,
	0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xe8, 0x01, 0x0a, 0x18, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x4e, 0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3f, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x65, 0x77,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x6e, 0x65, 0x77,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x69, 0x6e,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x50, 0x61, 0x69,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3f, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x8c,
	0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3d,
	0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x0c, 0x6e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x89, 0x01,
	0x0a, 0x11, 0x4f, 0x6e, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x03, 0x64, 0x65, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x65, 0x78, 0x52, 0x03, 0x64, 0x65, 0x78, 0x22, 0x4d, 0x0a, 0x12, 0x4f, 0x6e, 0x4e,
	0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x73, 0x64, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x55, 0x73, 0x64,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x31, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65,
	0x31, 0x64, 0x12, 0x20, 0x0a, 0x03, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x78, 0x52,
	0x03, 0x64, 0x65, 0x78, 0x22, 0x4f, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x47, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x15, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x91,
	0x01, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x41, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0xe0, 0x02, 0x0a, 0x11, 0x4f, 0x6e, 0x50, 0x61, 0x69, 0x72, 0x53, 0x79, 0x6e,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x30, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x30, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x31, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x30, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x03, 0x64, 0x65, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x78,
	0x52, 0x03, 0x64, 0x65, 0x78, 0x22, 0x4d, 0x0a, 0x12, 0x4f, 0x6e, 0x50, 0x61, 0x69, 0x72, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0xb7, 0x02, 0x0a, 0x1a, 0x4f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x31, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0a, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x31, 0x68, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x32, 0x34, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x32,
	0x34, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x37,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73,
	0x65, 0x37, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x5f,
	0x33, 0x30, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65,
	0x61, 0x73, 0x65, 0x33, 0x30, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x03,
	0x64, 0x65, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x78, 0x52, 0x03, 0x64, 0x65, 0x78, 0x22, 0x56,
	0x0a, 0x1b, 0x4f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x50, 0x0a, 0x14, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c,
	0x0a, 0x18, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e,
	0x45, 0x5f, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16,
	0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45, 0x5f,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0xdc, 0x04, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x53, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48,
	0x6f, 0x74, 0x12, 0x1e, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x5f, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x12, 0x22, 0x2e, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x4b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4e,
	0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1c, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0a, 0x4f, 0x6e, 0x4e, 0x65, 0x77, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4f, 0x6e, 0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x6e,
	0x4e, 0x65, 0x77, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0a, 0x4f, 0x6e, 0x50, 0x61, 0x69, 0x72, 0x53, 0x79, 0x6e, 0x63,
	0x12, 0x1c, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x6e, 0x50,
	0x61, 0x69, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x6e, 0x50, 0x61, 0x69,
	0x72, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x66, 0x0a, 0x13, 0x4f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x25, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x6e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_token_token_proto_rawDescOnce sync.Once
	file_token_token_proto_rawDescData = file_token_token_proto_rawDesc
)

func file_token_token_proto_rawDescGZIP() []byte {
	file_token_token_proto_rawDescOnce.Do(func() {
		file_token_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_token_token_proto_rawDescData)
	})
	return file_token_token_proto_rawDescData
}

var file_token_token_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_token_token_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_token_token_proto_goTypes = []interface{}{
	(InternalEngineStatus)(0),           // 0: token.api.InternalEngineStatus
	(*Dex)(nil),                         // 1: token.api.Dex
	(*Ping)(nil),                        // 2: token.api.Ping
	(*Hot)(nil),                         // 3: token.api.Hot
	(*HotList)(nil),                     // 4: token.api.HotList
	(*SubscribeHotRequest)(nil),         // 5: token.api.SubscribeHotRequest
	(*SubscribeHotResponse)(nil),        // 6: token.api.SubscribeHotResponse
	(*NewToken)(nil),                    // 7: token.api.NewToken
	(*NewTokenList)(nil),                // 8: token.api.NewTokenList
	(*SubscribeNewPairRequest)(nil),     // 9: token.api.SubscribeNewPairRequest
	(*SubscribeNewPairResponse)(nil),    // 10: token.api.SubscribeNewPairResponse
	(*GetNewPairRequest)(nil),           // 11: token.api.GetNewPairRequest
	(*GetNewPairResponse)(nil),          // 12: token.api.GetNewPairResponse
	(*OnNewTokenRequest)(nil),           // 13: token.api.OnNewTokenRequest
	(*OnNewTokenResponse)(nil),          // 14: token.api.OnNewTokenResponse
	(*SearchTokenResult)(nil),           // 15: token.api.SearchTokenResult
	(*SearchTokenResultList)(nil),       // 16: token.api.SearchTokenResultList
	(*SearchTokenRequest)(nil),          // 17: token.api.SearchTokenRequest
	(*SearchTokenResponse)(nil),         // 18: token.api.SearchTokenResponse
	(*OnPairSyncRequest)(nil),           // 19: token.api.OnPairSyncRequest
	(*OnPairSyncResponse)(nil),          // 20: token.api.OnPairSyncResponse
	(*OnTokenPriceChangedRequest)(nil),  // 21: token.api.OnTokenPriceChangedRequest
	(*OnTokenPriceChangedResponse)(nil), // 22: token.api.OnTokenPriceChangedResponse
}
var file_token_token_proto_depIdxs = []int32{
	1,  // 0: token.api.Hot.dex:type_name -> token.api.Dex
	3,  // 1: token.api.HotList.hot:type_name -> token.api.Hot
	0,  // 2: token.api.SubscribeHotResponse.status:type_name -> token.api.InternalEngineStatus
	4,  // 3: token.api.SubscribeHotResponse.hot_list:type_name -> token.api.HotList
	2,  // 4: token.api.SubscribeHotResponse.ping:type_name -> token.api.Ping
	1,  // 5: token.api.NewToken.dex:type_name -> token.api.Dex
	7,  // 6: token.api.NewTokenList.new_token:type_name -> token.api.NewToken
	0,  // 7: token.api.SubscribeNewPairResponse.status:type_name -> token.api.InternalEngineStatus
	8,  // 8: token.api.SubscribeNewPairResponse.new_token_list:type_name -> token.api.NewTokenList
	2,  // 9: token.api.SubscribeNewPairResponse.ping:type_name -> token.api.Ping
	0,  // 10: token.api.GetNewPairResponse.status:type_name -> token.api.InternalEngineStatus
	8,  // 11: token.api.GetNewPairResponse.new_token_list:type_name -> token.api.NewTokenList
	1,  // 12: token.api.OnNewTokenRequest.dex:type_name -> token.api.Dex
	0,  // 13: token.api.OnNewTokenResponse.status:type_name -> token.api.InternalEngineStatus
	1,  // 14: token.api.SearchTokenResult.dex:type_name -> token.api.Dex
	15, // 15: token.api.SearchTokenResultList.results:type_name -> token.api.SearchTokenResult
	0,  // 16: token.api.SearchTokenResponse.status:type_name -> token.api.InternalEngineStatus
	16, // 17: token.api.SearchTokenResponse.result_list:type_name -> token.api.SearchTokenResultList
	1,  // 18: token.api.OnPairSyncRequest.dex:type_name -> token.api.Dex
	0,  // 19: token.api.OnPairSyncResponse.status:type_name -> token.api.InternalEngineStatus
	1,  // 20: token.api.OnTokenPriceChangedRequest.dex:type_name -> token.api.Dex
	0,  // 21: token.api.OnTokenPriceChangedResponse.status:type_name -> token.api.InternalEngineStatus
	5,  // 22: token.api.Token.SubscribeHot:input_type -> token.api.SubscribeHotRequest
	9,  // 23: token.api.Token.SubscribeNewPair:input_type -> token.api.SubscribeNewPairRequest
	11, // 24: token.api.Token.GetNewPair:input_type -> token.api.GetNewPairRequest
	17, // 25: token.api.Token.SearchToken:input_type -> token.api.SearchTokenRequest
	13, // 26: token.api.Token.OnNewToken:input_type -> token.api.OnNewTokenRequest
	19, // 27: token.api.Token.OnPairSync:input_type -> token.api.OnPairSyncRequest
	21, // 28: token.api.Token.OnTokenPriceChanged:input_type -> token.api.OnTokenPriceChangedRequest
	6,  // 29: token.api.Token.SubscribeHot:output_type -> token.api.SubscribeHotResponse
	10, // 30: token.api.Token.SubscribeNewPair:output_type -> token.api.SubscribeNewPairResponse
	12, // 31: token.api.Token.GetNewPair:output_type -> token.api.GetNewPairResponse
	18, // 32: token.api.Token.SearchToken:output_type -> token.api.SearchTokenResponse
	14, // 33: token.api.Token.OnNewToken:output_type -> token.api.OnNewTokenResponse
	20, // 34: token.api.Token.OnPairSync:output_type -> token.api.OnPairSyncResponse
	22, // 35: token.api.Token.OnTokenPriceChanged:output_type -> token.api.OnTokenPriceChangedResponse
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_token_token_proto_init() }
func file_token_token_proto_init() {
	if File_token_token_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_token_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeHotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeHotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTokenList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeNewPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeNewPairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNewPairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnNewTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnNewTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTokenResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTokenResultList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPairSyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPairSyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTokenPriceChangedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_token_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTokenPriceChangedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_token_token_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*SubscribeHotResponse_HotList)(nil),
		(*SubscribeHotResponse_Ping)(nil),
	}
	file_token_token_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*SubscribeNewPairResponse_NewTokenList)(nil),
		(*SubscribeNewPairResponse_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_token_token_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_token_proto_goTypes,
		DependencyIndexes: file_token_token_proto_depIdxs,
		EnumInfos:         file_token_token_proto_enumTypes,
		MessageInfos:      file_token_token_proto_msgTypes,
	}.Build()
	File_token_token_proto = out.File
	file_token_token_proto_rawDesc = nil
	file_token_token_proto_goTypes = nil
	file_token_token_proto_depIdxs = nil
}
